# Generated by Django 5.1.6 on 2025-02-27 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisao_ocupacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=255, verbose_name='Tipo de documento PGT')),
                ('municipio', models.CharField(max_length=255, verbose_name='Município')),
                ('assentamento', models.CharField(max_length=255)),
                ('nome_t1', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Documento PGT',
                'verbose_name_plural': 'Documentos PGT',
            },
        ),
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
            },
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='PlanilhaMonitoramento',
        ),
        migrations.AlterModelOptions(
            name='documentorecebido',
            options={'verbose_name': 'Documento Recebido', 'verbose_name_plural': 'Documentos Recebidos'},
        ),
        migrations.AlterModelOptions(
            name='laudo',
            options={'verbose_name': 'Laudo', 'verbose_name_plural': 'Laudos'},
        ),
        migrations.AlterModelOptions(
            name='parecer',
            options={'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.RemoveField(
            model_name='documentorecebido',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documentorecebido',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='documentorecebido',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='documentorecebido',
            name='remetente',
        ),
        migrations.RemoveField(
            model_name='documentorecebido',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='conclusao',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='data',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='laudo',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='documentorecebido',
            name='municipio',
            field=models.CharField(default='Unidentified', max_length=255, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentorecebido',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='documentorecebido',
            name='status',
            field=models.CharField(default='Recebido', max_length=100),
        ),
        migrations.AddField(
            model_name='documentorecebido',
            name='tipo_documento',
            field=models.CharField(default='Unidentified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='municipio',
            field=models.CharField(default='Unidentified', max_length=255, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laudo',
            name='tipo_laudo',
            field=models.CharField(default='Unidentified', max_length=255, verbose_name='Tipo de Laudo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parecer',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='parecer',
            name='municipio',
            field=models.CharField(default='Unidentified', max_length=255, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parecer',
            name='tipo_parecer',
            field=models.CharField(default='Unidentified', max_length=255, verbose_name='Tipo de Parecer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='data_recebimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
