# Generated by Django 5.1.6 on 2025-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisao_ocupacional', '0002_documentopgt_planilha_delete_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='assentamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assentamento'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='codigo_sipra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código SIPRA'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='lote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='modalidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='tecnico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnico'),
        ),
    ]
