# Generated by Django 5.1.6 on 2025-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisao_ocupacional', '0003_laudo_arquivo_laudo_assentamento_laudo_codigo_sipra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
