# Generated by Django 5.1.6 on 2025-02-27 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisao_ocupacional', '0004_alter_laudo_data_emissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentopgt',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='documentopgt',
            name='autenticador',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autenticador'),
        ),
        migrations.AddField(
            model_name='documentopgt',
            name='codigo_sipra',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código SIPRA'),
        ),
        migrations.AddField(
            model_name='documentopgt',
            name='segundo_relatorio',
            field=models.CharField(default='Não', max_length=10, verbose_name='Segundo Relatório'),
        ),
        migrations.AddField(
            model_name='documentopgt',
            name='tipo_documentopgt',
            field=models.CharField(default='Undefined', max_length=100, verbose_name='Tipo de documento PGT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentopgt',
            name='assentamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assentamento'),
        ),
        migrations.AlterField(
            model_name='documentopgt',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='documentopgt',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='documentopgt',
            name='nome_t1',
            field=models.CharField(blank=True, default='Undefined', max_length=100, verbose_name='Nome T1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentopgt',
            name='objetivo',
            field=models.CharField(blank=True, default='Undefined', max_length=100, verbose_name='Objetivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='data_recebimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='observacoes',
            field=models.TextField(blank=True, default='Undefined', verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='status',
            field=models.CharField(default='Recebido', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentorecebido',
            name='tipo_documento',
            field=models.CharField(max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='arquivo',
            field=models.CharField(blank=True, default='Undefined', max_length=255, verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='assentamento',
            field=models.CharField(blank=True, default='Undefined', max_length=100, verbose_name='Assentamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='codigo_sipra',
            field=models.CharField(blank=True, default='Undefined', max_length=50, verbose_name='Código SIPRA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='lote',
            field=models.CharField(blank=True, default='Undefined', max_length=50, verbose_name='Lote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='modalidade',
            field=models.CharField(blank=True, default='Undefined', max_length=100, verbose_name='Modalidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='tecnico',
            field=models.CharField(blank=True, default='Undefined', max_length=100, verbose_name='Técnico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laudo',
            name='tipo_laudo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Laudo'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='tipo_parecer',
            field=models.CharField(max_length=100, verbose_name='Tipo de Parecer'),
        ),
        migrations.AlterField(
            model_name='planilha',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='planilha',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
