# Generated by Django 5.1.6 on 2025-02-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisao_ocupacional', '0005_rename_tipo_documento_to_tipo_documentopgt'),
    ]

    operations = [
        # Deixe vazio, pois não precisamos fazer nada
    ]
